keys:
  - &user_roy age13ldedhh6ymava0d5dn54860a3f799gufknre9lfegegjt9ytes2qq5qgmr
  - &system age1h672rl8yp4utgqx0ndxv2wtg5fw69vznyxa2p699rq4ku6x2afrslt7x2u
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *user_roy
      - *system
