[general]
import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[terminal]
shell = "fish"

[font]
normal = { family = "Ubuntu Mono" }
italic = { family = "Ubuntu Mono" }
bold = { family = "Ubuntu Mono" }
size = 18

[window]
decorations = "full"
opacity = 1
